name: Sync Fork

on:
  schedule:
    - cron: '*/10 * * * *' 
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync upstream
        run: |
          git remote add upstream https://github.com/InsansaTechnoledge/no-due
          git fetch upstream
      
          # Sync main
          git checkout -B main origin/main
          git merge upstream/main --no-edit
          git push origin main
      
          # Sync develop
          git checkout -B develop origin/develop
          git merge upstream/develop --no-edit
          git push origin develop
